// Test generated by RoostGPT for test rest-assured-shakul using AI Type Open AI and AI Model gpt-4-1106-preview

// Test generated for /v2.1/flavors/10/flavor-access_get for http method type GET in rest-assured framework

// RoostTestHash=83e47da257

{
    "get": {
        "operationId": "returnaccesslist",
        "summary": "Return access list",
        "description": "Returns access list by flavor id.\n",
        "produces": ["application/json"],
        "responses": {
            "200": {
                "description": "200 response",
                "examples": {
                    "application/json": {
                        "flavor_access": [
                            {
                                "tenant_id": "openstack",
                                "flavor_id": "10"
                            },
                            {
                                "tenant_id": "fake_tenant",
                                "flavor_id": "10"
                            }
                        ]
                    }
                }
            }
        }
    }
}

