// Test generated by RoostGPT for test rest-assured-metric using AI Type Open AI and AI Model gpt-4

// Test generated for /v2.0/metering/metering-label-rules/{metering-label-rule-id}_get for http method type GET in rest-assured framework

// RoostTestHash=987f45854d

package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import org.junit.Test;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class metering-label-rules_metering-label-rule-idGetTest {

    @Test
    public void metering-label-rules_metering-label-rule-id_get_Test() {
        RestAssured.baseURI = System.getenv("BASE_URL");

        try (BufferedReader reader = new BufferedReader(new FileReader("src/test/java/com/bootexample4/RoostTest/metering-label-rules_metering-label-rule-id_get.csv"))) {
            String headerLine = reader.readLine();
            String[] headers = headerLine.split(",");

            String line;
            while ((line = reader.readLine()) != null) {
                String[] data = line.split(",");

                Map<String, String> map = new HashMap<>();
                for (int i = 0; i < headers.length; i++) {
                    map.put(headers[i], data[i]);
                }

                RequestSpecification request = given()
                        .contentType(ContentType.JSON)
                        .pathParam("metering-label-rule-id", map.get("metering-label-rule-id"));

                Response response = request.when()
                        .get("/v2.0/metering/metering-label-rules/{metering-label-rule-id}")
                        .then()
                        .extract().response();

                int statusCode = response.statusCode();
                switch (statusCode) {
                    case 200:
                        validateSuccessResponse(response);
                        break;
                    case 400:
                        validateErrorResponse(response);
                        break;
                    case 404:
                        validateNotFoundResponse(response);
                        break;
                    case 422:
                        validateUnprocessableEntityResponse(response);
                        break;
                    default:
                        System.out.println("Unexpected status code: " + statusCode);
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void validateSuccessResponse(Response response) {
        response.then().body("id", equalTo(map.get("metering-label-rule-id")));
        System.out.println("Validated 200 response");
    }

    private void validateErrorResponse(Response response) {
        response.then().body("error", is(notNullValue()));
        System.out.println("Validated 400 response");
    }

    private void validateNotFoundResponse(Response response) {
        response.then().body("error", equalTo("Not Found"));
        System.out.println("Validated 404 response");
    }

    private void validateUnprocessableEntityResponse(Response response) {
        response.then().body("error", equalTo("Unprocessable Entity"));
        System.out.println("Validated 422 response");
    }
}
